### PR TITLE
Remove the ad-hoc type intersection code

### PR DESCRIPTION
**Pull request by linas**
Replace the type intersection code with TypeIntersectionLink.

This uncovered two minor bugs in the unify glob-matching unit tests, now fixed.
The glob-matching was asymmetrical, prefering unification on one side but not
the other; it's now fully symmetrical.  (I think its not hard to go back to the
asymmetric version, but that doesn't make sense to me).

@ngeiswei take a look and please merge if you agree...

### CODE REVIEW

**Comment by ngeiswei** [comment]
@kasimebrahim could you have a look at @linas fix? Note that he has changed the expected result of `UnifyGlobUTest::test_type_intersection_5()`.

**Comment by kasimebrahim** [comment]
I think, I might have been wrong on the glob specification @linas mentioned. `Globs can only match lists, even if they are just singletons.` is the key here. I assumed globs could match any thing and that was why I added `UnifyGlobUTest::test_type_intersection_5()`[now just redundant with `UnifyGlobUTest::test_type_intersection_3`].

I thought `(Glob "$foo")` is equivalent to 
<pre>
TypedVariableLink
    VariableNode   "$foo"
    Interval
        Number 0
        Number 'inf
</pre>

But regarding symmetry, on `UnifyGlobUTest::test_unify_typed_3` I still dont think `{{{U, X}, U}, {{Y, Z, al(LIST_LINK, HandleSeq{})}, al(LIST_LINK, HandleSeq{})}}` should be included as a solution because `X` is less abstract than `U` due to its narrow interval [1, 1] than [0, 2].
Even if `X` and `U` have the same type restriction and interval including both {{X, U}, X} and {{X, U}, U} doesn't make sense because the second argument of the block is just a type intersection. Meaning only the type restriction matters which is type(X) == type(U). So having both is redundant.

**Comment by ngeiswei** [comment]
@kasimebrahim, I think I agree, `UnifyGlobUTest::test_type_intersection_5()` was indeed wrong.

And I also agree about `UnifyGlobUTest::test_unify_typed_3`. However, upon inspecting it I wonder why the solution

```
{{{U, al(LIST_LINK, {X, Z})}, al(LIST_LINK, {X, Z})},
 {{Y, al(LIST_LINK, HandleSeq{})}, al(LIST_LINK, HandleSeq{})}}
```

isn't included, it seems valid as well, isn't it?

**Comment by kasimebrahim** [comment]
@ngeiswei that is because XYZ are ordered.

**Comment by ngeiswei** [comment]
> @ngeiswei that is because XYZ are ordered.

Yes, but if Y is empty isn't XYZ equivalent to XZ?

**Comment by kasimebrahim** [comment]
Yep that is good point.

**Comment by ngeiswei** [comment]
@kasimebrahim , maybe I merge @linas PR now and you'll take care the remaining bits in subsequent PRs?

**Comment by kasimebrahim** [comment]
Yeah sure.

**Comment by ngeiswei** [comment]
OK, I've merged and added this issue https://github.com/singnet/ure/issues/21 as a reminder.

**Comment by linas** [comment]
> I thought `(Glob "$foo")` is equivalent to
```
TypedVariableLink
    VariableNode   "$foo"
    Interval
        Number 0
        Number 'inf
```
It should have been that, but due to historical accident, it came out equivalent to `[1, inf]` and changing it now seems too much of a tear-up.

**Pull request merged**
