### PR TITLE
do not pass atomspace to Atom.createAtom

### PR DESCRIPTION
**Pull request by noskill**
updating cython wrapper in https://github.com/opencog/atomspace/pull/2313

### CODE REVIEW

**Comment by linas** [comment]
@vsbogd if unit tests are passing locally, please do merge this and the atomspace pull req.

**Comment by noskill** [comment]
cython tests are passing locally

**Comment by vsbogd** [comment]
I don't have permission, @ngeiswei, could you please merge both PRs

**Comment by vsbogd** [comment]
@ngeiswei , I mean:
https://github.com/opencog/ure/pull/32
https://github.com/opencog/atomspace/pull/2313

**Comment by ngeiswei** [comment]
Thanks for merging in my absence. @vsbogd, I've added the opencog team developers https://github.com/orgs/opencog/teams/opencog-developers which you are part of, so next time you should be able to merge.

**Comment by vsbogd** [comment]
Thank you @ngeiswei !

**Pull request merged**
