### PR TITLE
Alter unit test to match new AtomSpace behavior.

### PR DESCRIPTION
**Pull request by linas**
The changes in opencog/atomspace#2685 alters how the utility
`is_constant()` works, which is used by `unify/Unify.cc` which is
used by `AndBIT::expand()` which alters the unit test results.

The new `is_constant()` is working correctly, however, it is possible
that `AndBIT::expand()` is broken or incorrect ... The `is_constant()`
is called with an empty variable list, and so indeed, the entire
clause is constant. But it does contain a variable, so maybe it was not
supposed to be? All the other clauses contain this variable, too, so
this seems very suspicious.

### CODE REVIEW

**Comment by linas** [comment]
Merging, because this block successful unit test for  opencog/atomspace#2685

**Comment by linas** [comment]
See #94 to track this change.

**Comment by ngeiswei** [comment]
It's not a bug, the empty `VariableList` is here to tell to consider the variables as constants.

**Comment by ngeiswei** [comment]
Wait, actually that's correct! Essentially cause `is_constant` has been fixed.

**Pull request merged**
