### PR TITLE
Use OpenCogFindPython macro to get Python dependencies uniformly.

### PR DESCRIPTION
**Pull request by vsbogd**
Use `OpenCogFindPython` macro to get Python dependencies uniformly.
Complementary PR to fix https://github.com/opencog/cogutil/issues/176 after merging https://github.com/opencog/cogutil/pull/211

### CODE REVIEW

**Comment by vsbogd** [comment]
@dagims , @linas , @ngeiswei  FYI.

**Comment by ngeiswei** [comment]
@vsbogd feel free to merge as you see fit.

**Comment by vsbogd** [comment]
@ngeiswei I don't have write permissions to this repo.

**Comment by ngeiswei** [comment]
I've added you.

**Comment by vsbogd** [comment]
Thanks!

**Pull request merged**
